name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle
      # Ensure dependency installation completed successfully
      continue-on-error: false
      
    - name: Run specs
      run: bundle exec rspec

    - name: Check host key
      run: |
        ssh -T 20.42.22.4
      
    - name: Set up SSH and deploy
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        chmod +x deploy_script.sh
        
        # Get runner IP address
        IP_ADDRESS=$(curl -s https://api64.ipify.org?format=text)
        
        # Whitelist runner IP address in EC2 security group
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.AWS_INSTANCE_SG_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr $IP_ADDRESS/32
        
        # Run deployment script
        EC2_INSTANCE_IP="ec2-54-92-184-233.compute-1.amazonaws.com" ./deploy_script.sh
        
        # Revoke runner IP address from EC2 security group
        aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.AWS_INSTANCE_SG_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr $IP_ADDRESS/32
